export const ORDER_FEED_CONNECT: 'ORDER_FEED_CONNECT' = 'ORDER_FEED_CONNECT';
export const ORDER_FEED_DISCONNECT: 'ORDER_FEED_DISCONNECT' = 'ORDER_FEED_DISCONNECT';

export const ORDER_FEED_WS_CONNECTING: 'ORDER_FEED_WS_CONNECTING' = 'ORDER_FEED_WS_CONNECTING';
export const ORDER_FEED_WS_OPEN: 'ORDER_FEED_WS_OPEN' = 'ORDER_FEED_WS_OPEN';
export const ORDER_FEED_WS_CLOSE: 'ORDER_FEED_WS_CLOSE' = 'ORDER_FEED_WS_CLOSE';
export const ORDER_FEED_WS_GET_MESSAGE: 'ORDER_FEED_WS_GET_MESSAGE' = 'ORDER_FEED_WS_GET_MESSAGE';

export const ORDER_FEED_WS_ERROR: 'ORDER_FEED_WS_ERROR' = 'ORDER_FEED_WS_ERROR';

// for ws with token
export const ORDER_PERSONAL_FEED_CONNECT: 'ORDER_PERSONAL_FEED_CONNECT' = 'ORDER_PERSONAL_FEED_CONNECT'; 
export const ORDER_PERSONAL_FEED_DISCONNECT: 'ORDER_PERSONAL_FEED_DISCONNECT' = 'ORDER_PERSONAL_FEED_DISCONNECT';

export const ORDER_PERSONAL_FEED_WS_CONNECTING: 'ORDER_PERSONAL_FEED_WS_CONNECTING' = 'ORDER_PERSONAL_FEED_WS_CONNECTING';
export const ORDER_PERSONAL_FEED_WS_OPEN: 'ORDER_PERSONAL_FEED_WS_OPEN' = 'ORDER_PERSONAL_FEED_WS_OPEN';
export const ORDER_PERSONAL_FEED_WS_CLOSE: 'ORDER_PERSONAL_FEED_WS_CLOSE' = 'ORDER_PERSONAL_FEED_WS_CLOSE';
export const ORDER_PERSONAL_FEED_WS_GET_MESSAGE: 'ORDER_PERSONAL_FEED_WS_GET_MESSAGE' = 'ORDER_PERSONAL_FEED_WS_GET_MESSAGE';

export const ORDER_PERSONAL_FEED_WS_ERROR: 'ORDER_PERSONAL_FEED_WS_ERROR' = 'ORDER_PERSONAL_FEED_WS_ERROR';


